### ISSUE TITLE
Comments metaboxes sometimes appear in Edit Post

### ISSUE THREAD

**Issue by fgilio** [solarissmoke/disable-comments-mu#9]
Hi!

I've a dev site in my local machine where I see both Comments metaboxes in posts already published, that I imported from the staging site.
Not when I create a new one, neither when I edit one of those new posts.

I was using the standard version of the plugin and later switch to the mu version.

Do you know what could cause this behavior? Otherwise, how can I help you debug it?

Regards!

**Comment by szepeviktor** [comment]
> You should delete all existing comments from the WordPress database before activating this plugin.

*from the README*

`wp comment delete $(wp comment list --format=ids)`

**Comment by fgilio** [comment]
I have no data in wp_comments nor in wp_commentmeta, both tables are empty.

Here is a screenshot of the metaboxes I get in, i think, all imported posts: https://www.dropbox.com/s/416s2529wlqqeiu/Screenshot%202016-03-01%2000.57.36.png?dl=0

**Comment by szepeviktor** [comment]
Maybe your import procedure was before activating `disable-comments-mu` or ignored some hooks.

**Comment by fgilio** [comment]
Yeah, thanks!

I used this query:
`UPDATE wp_posts SET comment_status = 'closed';`

**Comment by solarissmoke** [comment]
Hmm... those meta boxes should be hidden even if comments are open (the plugin removes support for comments). I will have a look some time and see why they are appearing.

**Comment by fgilio** [comment]
Thank you @solarissmoke

**Comment by solarissmoke** [comment]
@fgilio I have tested on a clean installation and cannot reproduce this issue. The only time the meta boxes are available is if a post already has comments on it (which is expected behaviour). In all other cases the meta boxes do not appear - even in the Screen Options list.

I'm not sure why you are seeing different behaviour - maybe another plugin is filtering `comments_open`? I'm going to close this for now but if you find where your issue is then feel free to reopen!

**Comment by fgilio** [comment]
Thank you @solarissmoke, I'll reopen if I find out what happened. It all seems ok now :D
